#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World  inside

if ! sudo apt-get update -y && sudo apt-get install -y nginx;
then
    echo -e \
"http {
    root /var/www/school;
    index index.html;
    server {
        listen 80;
        location \ {
        }
    }
}
events {
}" > /etc/nginx/nginx.conf
    mkdir -p /var/www/school
    echo "Hello World!" > \
	/var/www/school/index.html
    if ! service nginx start;
    then
	"Problem starting nginx"
	exit 1
    fi
else
    echo "Could not install nginx"
    exit 1
fi
exit 0
