#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World  inside
sudo apt -y update 
sudo apt install -y nginx
# Configure nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
#create the web directory
sudo mkdir -p /var/www/html
#configure firewall to allow both http and https traffic
sudo ufw allow 'nginx full'
sudo ufw reload
#configure ownership and permissions
sudo chown -R "$USER":"$USER" /var/www
sudo chmod -R 755 /var/www
#creating an index file to be displayed on the browser
echo "Hello World!" > /var/www/html/index.html
# Restart nginx without using systemctl
sudo service nginx restart