#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World  inside

SERVER_CONFIG=\
"server {
        listen 80;
        listen [::]:80;

        root /var/www/html/alx;

        # Add index.php to the list if you are using PHP
        index index.html index.nginx-debian.html;

        server_name _;

        location / {
            root /var/www/html/alx;
        }
}"
#update and install nginx
sudo apt-get -y update

if ! sudo apt-get install -y nginx;
then
    echo "Installation Dropped"
    exit 1
else
    #make the web dir
    sudo mkdir -p /var/www/html/alx
    #change ownership of the folder
    sudo chown -R $USER:$USER /var/www/html/alx
    sudo chmod -R 755 /var/www/html
    #create the index file
    sudo echo "Hello World!" > /var/www/html/alx/index.html
    #make the config file
    sudo echo "$SERVER_CONFIG" > /etc/nginx/sites-available/alx
    #create symbolic link to the config file in site-available
    ln -s /etc/nginx/sites-available/alx /etc/nginx/sites-enabled/alx
    #removing the default config file serving on port 80
    sudo rm /etc/nginx/sites-enabled/default
    #allow traffic through the firewall
    sudo ufw allow 'Nginx HTTP'
    #restart nginx
    sudo service nginx restart
    exit 0
fi
