#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World  inside

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root   var/www/html;
    index  index.html;

    location /redirect_me {
        return 301;
    }
    
    error_page 404 /404.html;
    location = /404.html{
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
