#!/usr/bin/env bash
# configures nginx response to add a header

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i '19 i \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx restart
