#!/usr/bin/env bash
# configures HAproxy

sudo apt-get update
sudo apt-get install -y haproxy
sudo sed -i '10 i ENABLED=1' /etc/default/haproxy
sudo sed -i '35 a \\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back' /etc/haproxy/haproxy.cfg
sudo sed -i '40 a \\nbackend http_back\n\tbalance roundrobin\n\tserver web-01 100.25.156.215:80 check\n\tserver web-02 100.26.20.85:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
